Desktop version pull request
alicemirigo92/alicemirigodesktop.github.io pull request #1
Opened 2022-12-10 19:07 UTC by alicemirigo92

Add desktop version
Add images
Add required transitions and animations
Have pairing program

2022-12-12 14:18 UTC, Qoosim reviewed
#  *Status: Invalidate* :red_circle:

Hi @alicemirigo92, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that did not make use of [new README template](https://github.com/microverseinc/readme-template). Kindly use that template to make your README professional.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-14 13:49 UTC, Olamarx requested changes
Hi @alicemirigo92, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

## Highlights
- Linters passed 👍🏼
- Media query ✔️ 

## Required Changes ♻️
_Check the comments under the review._

### I would have made these comments inline but they have been merged as it is a modification milestone
- [ ] Just as it is in the figma, kindly make the text align to the left but it should not pass the middle of the page.
### Your work
![image](https://user-images.githubusercontent.com/86200356/207598447-db22f6d6-5466-43e3-b3f5-36d1561ab670.png)

### Figma design
![image](https://user-images.githubusercontent.com/86200356/207598565-55477c55-7232-4784-8ae1-daed8dd44d22.png)
- [ ] Kindly reduce the space between your start collaboration and the text above it.
### Your work
![image](https://user-images.githubusercontent.com/86200356/207599495-eca83a85-5da7-4deb-a128-8c9ae15bb08f.png)
### Figma design
![image](https://user-images.githubusercontent.com/86200356/207599648-a5d6b2bc-d1e8-4ece-84df-3ba961c19cce.png)
- [ ] Kindly remove the spaces that are not needed by giving the webpage a width, you can give it 100% and it should work.

### Your work
![image](https://user-images.githubusercontent.com/86200356/207611114-06e54441-95a8-4631-a900-f547a9ca4524.png)

### figma
![image](https://user-images.githubusercontent.com/86200356/207611389-89b100b5-3736-48a6-89cb-953839c5c531.png)

- [ ] Same thing applies to this also. The width overflows

### Your work
![image](https://user-images.githubusercontent.com/86200356/207611699-5b58bcbe-f5d8-48a3-91da-e5db26c60b3e.png)

### Figma
![image](https://user-images.githubusercontent.com/86200356/207611800-8ed8ef55-6634-4a7a-be1b-183b9376179e.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 14:34 UTC, joskalenda requested changes
Hi @alicemirigo92 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌

⚠️  You have submitted a project, that has failed linters, please fix them and resubmit your work

<img src="https://media4.giphy.com/media/uqMQsE4HKYvfnjhIRQ/giphy.gif"/>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

-----
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._ 🟢

2022-12-16 09:38 UTC, OyePriscilla approved these changes
Hi @alicemirigo92  👍 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Linters check passed ✔️ 
Good commit messages ✔️ 

## Optional suggestions
[optional] Please kindly ensure to observe `Github flow` for your subsequent PR. (Make main branch to be the default) 👍 
[optional] I noticed that you app is not responsive as expected, please take your time to work over it. 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 09:38 UTC, OyePriscilla commented on style.css
> +  }
- [optional] Please kindly give this button element tect color of #fff as we have it in figma. 👍

2022-12-16 10:04 UTC, merged