Add popup pull request
alicemirigo92/alicemirigodesktop.github.io pull request #7
Opened 2023-01-04 23:01 UTC by alicemirigo92

2023-01-05 23:24 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @alicemirigo92 @Zeph180 :wave: 

Good Job so far. :+1:  
There are some issues you need to fix before you move to the next project.

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Linters checks are passing
✔️ Use GitHub Flow
✔️ Meaningful commit messages.
✔️ Correctly implemented an array of objects to store JavaScript objects.
✔️ Correctly implemented Modal.

## Required Changes ♻️

- [ ] Kindly implement `Previous project` and `Next project` at the bottom of the popup window according to the [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) for `Desktop` version.
***Figma Design***
![Screenshot from 2023-01-06 05-29-38](https://user-images.githubusercontent.com/60083437/210899797-a6e74966-fd27-4024-b7b2-995a6f2c13cd.png)

_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 23:24 UTC, Tufahel commented on modalstyle.css
> +  }
- [ ] Kindly fix the position and color of the `name` and `arrow` inside the `See Live` button according to the [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
***Figma Design***
![Screenshot from 2023-01-06 04-46-00](https://user-images.githubusercontent.com/60083437/210894609-db7ae1c6-6bcf-4dd9-88eb-59c9046ecfa9.png)
***Your Design***
![Screenshot from 2023-01-06 04-46-49](https://user-images.githubusercontent.com/60083437/210894733-a39ed207-8a6b-4a29-b60c-7c61e18f9b4d.png)

2023-01-05 23:24 UTC, Tufahel commented on modalstyle.css
> +  }
- Great Work on implementing `hover` on the buttons. :+1: 

- [ ] Kindly fix the position and the color of the `name` and `GitHub` link inside the `See Source` button.
***Figma Design***
![Screenshot from 2023-01-06 05-15-17](https://user-images.githubusercontent.com/60083437/210898188-a083fab3-680c-45b2-b386-f5d77be358a9.png)
***Your Design***
![Screenshot from 2023-01-06 04-54-00](https://user-images.githubusercontent.com/60083437/210895656-4ce67054-0d5d-4357-9fbc-1453aef1f710.png)

2023-01-05 23:24 UTC, Tufahel commented on modalstyle.css
> +  }
- [ ] Kindly follow the given [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9), to `style the fonts, the position of the text and for margin/padding`.
***Figma Design***
![Screenshot from 2023-01-06 04-57-59](https://user-images.githubusercontent.com/60083437/210896314-c6084afa-2ee1-4bbc-a8c1-973a3970ca1d.png)
***Your Design***
![Screenshot from 2023-01-06 04-59-29](https://user-images.githubusercontent.com/60083437/210896357-71032b0d-2cc2-445c-9bec-f5090a4a9ae1.png)

2023-01-05 23:24 UTC, Tufahel commented on index.js
> +        <p>${projects[b.id].title}</p>
- [ ] As the project name is a title, it is recommended to use `<hx></hx>` for titles, not `<p></p>` tag, to increase HTML accessibility.
  - Such as you can consider using `<h2></h2>` or `<h3></h3>` tag.

- [ ] Kindly follow the [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9) to style the title.
***Your Design***
![Screenshot from 2023-01-06 05-08-46](https://user-images.githubusercontent.com/60083437/210897400-4fc738b6-98bf-43f0-9b57-01dc38ae8c2a.png)
***Figma Design***
![Screenshot from 2023-01-06 05-07-58](https://user-images.githubusercontent.com/60083437/210897337-0d208ac4-9b10-40e4-9b0d-93930ff5e7da.png)

2023-01-05 23:24 UTC, Tufahel commented on modalstyle.css
> +@media (max-width: 768px) {
- [ ] Kindly fix the `Style` of the modal of the `Mobile` version. Your project style looks the same for the `Mobile` and `Desktop` versions. But in [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9), styles are different in both cases.
***Your Design***
![Screenshot from 2023-01-06 05-10-02](https://user-images.githubusercontent.com/60083437/210898012-434a1418-cbac-42c7-9337-295c858adaf4.png)
***Figma Design***
![Screenshot from 2023-01-06 05-14-31](https://user-images.githubusercontent.com/60083437/210898093-cb5a6c38-d198-4b65-ba19-2f3412cc1812.png)

2023-01-06 12:02 UTC, brainconnect93 requested changes
### Hi @alicemirigo92, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 12:02 UTC, brainconnect93 commented on index.js
> +    div.className = 'popup';
- [ ] As requested by the previous reviewer, I would kindly suggest you follow the Figma template as much as possible for your modal pop-up design

Below 👇  is a video explanation of what you need to work on

[screen-capture (3).webm](https://user-images.githubusercontent.com/78634841/211008759-03a755de-a4ef-4482-a23c-7341316df24b.webm)

2023-01-06 12:35 UTC, alicemirigo92 commented
@brainconnect93 Done

2023-01-06 15:49 UTC, iambenkis approved these changes
### Hi  @alicemirigo92    , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights

GitHub review feature :heavy_check_mark:
Inline comment :heavy_check_mark: 
The comments are given in a friendly and polite manner :heavy_check_mark: 
Explain why changes were suggested :heavy_check_mark: 

## Optional 
**_Every comment with the [**OPTIONAL**] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@iambenkis** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 15:59 UTC, merged